analyzer:
  errors:
    prefer_const_constructors: warning
    must_be_immutable: warning
    unnecessary_null_checks: warning
    avoid_unnecessary_containers: warning
    prefer_final_locals: warning
    avoid_print: warning

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    always_use_package_imports: true
    sort_constructors_first: true
    avoid_unnecessary_containers: true
    unnecessary_null_checks: true
    prefer_const_declarations: true
    annotate_overrides: true
    unnecessary_this: true
    constant_identifier_names: true
